openapi: 3.0.0
info:
  title: Bid Box
  version: 1.0.0
  description: API Documentation for Bid Box
tags: 
  - name: User
    description: Operations related to User
paths:
  /user/register:
    $ref: "./routes/register-user.yaml"

  /user/login:
    $ref: "./routes/login-user.yaml"

  /user/refresh:
    $ref: "./routes/refresh-user.yaml"
